version: '3'
services:
    web:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "3000:80"
        volumes:
            - ./src/:/var/www/html/
            - ../newtondreams-lib/dist/:/var/www/html/js/core/dist/
            - ../newtondreams-lib/docs/:/var/www/html/js/core/docs/
